services:
  lb:
    image: traefik:latest
    command: --web --docker --docker.domain=docker.localhost --logLevel=DEBUG
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml
    ports:
      - "9000:80"
      - "8081:80"
      - "9001:8080"
    networks:
      - ussd-net

  nginx:
    image: nginx
    volumes:
      - ./:/usr/share/nginx/html/
    labels:
      - "traefik.frontend.rule=PathPrefix:/static/"
      - "traefik.backend=nginx"
      - "traefik.port=80"
      - "traefik.weight=5"
    networks:
      - ussd-net

  db:
    image: postgres:14
    environment:
      - POSTGRES_DB=django-ussd-airflow
      - POSTGRES_PASSWORD=django-ussd-airflow
    ports:
      - 5444:5432
    labels:
      - "traefik.enable=false"
    networks:
      - ussd-net

  rabbitmq:
    image: rabbitmq:3.12-management
    ports:
      - "15680:15672"
    networks:
      - ussd-net

  app:
    build: .
    depends_on:
      - db
      - rabbitmq
      - dynamodb
    volumes:
      - ./:/usr/src/app
      - $HOME/.aws:/root/.aws
    command: bash -c "./wait-for-it.sh -t 300 db:5432 && ./run.sh"
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq//
      - CODACY_PROJECT_TOKEN=7911468d4aa94f0f941148a355a953d0
      - CODECOV_TOKEN=b9e923ec-1dea-4111-bc1c-ecaf28c0f0da
      - 'DATABASE_URL=postgres://postgres:django-ussd-airflow@db:5432/django-ussd-airflow'
      - TEST_VARIABLE=variable_test
      - ENVIRONMENT=sample_variable_two
      - DYNAMODB_TABLE=journeyTable
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
      - AWS_DEFAULT_REGION=us-east-1
    labels:
      - "traefik.frontend.rule=PathPrefix:/"
      - "traefik.backend=web"
      - "traefik.port=80"
      - "traefik.weight=3"
    ports:
      - 8080:80
    networks:
      - ussd-net

  editor:
    image: mwaaas/ussd_airflow_editor
    ports:
      - 8009:80
    networks:
      - ussd-net

  worker:
    build: .
    depends_on:
      - db
      - rabbitmq
    command: ./worker_server.sh
    volumes:
      - ./:/usr/src/app
    environment:
      -  C_FORCE_ROOT=true
      -  CELERY_BROKER_URL=amqp://guest:guest@rabbitmq//
      -  DYNAMODB_TABLE=journeyTable
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
      - AWS_DEFAULT_REGION=us-east-1
    labels:
      - "traefik.enable=false"
    networks:
      - ussd-net

  compile_documentation:
    build: .
    volumes:
      - ./:/usr/src/app
    command: make -C /usr/src/app/docs html
    labels:
      - "traefik.enable=false"
    networks:
      - ussd-net

  documentation:
    image: python:3.11-alpine
    depends_on:
      - compile_documentation
    working_dir: /usr/src/app/docs/_build/html
    volumes:
      - ./docs/_build/html:/usr/src/app/docs/_build/html
    command: python -m http.server
    ports:
      - "7000:8000"
    labels:
      - "traefik.enable=false"
    networks:
      - ussd-net

  dynamodb:
    image: amazon/dynamodb-local:latest
    ports:
      - "8781:8000"
    networks:
      - ussd-net

  ansible:
    image: cytopia/ansible:latest
    depends_on:
      - dynamodb
    volumes:
      - $HOME/.aws:/root/.aws
      - ./:/usr/src/app
    networks:
      - ussd-net

networks:
  ussd-net:
